#!/usr/bin/env zsh
NOTEDIR=${HOME}/Git/notes/
cd $NOTEDIR
NOTE=`ls -1 ${NOTEDIR} | dmenu -b -nb darkblue -nf lightblue -sb blue -sf lightblue`
FILELOCATION="${NOTEDIR}${NOTE}"
LOGLOCATION="${NOTEDIR}notes.log"
mkdir -p ${NOTEDIR}
if [[ -n $NOTE ]] 
then
    TIMESTAMP=`date`
    STRING="$TIMESTAMP : edited  file $FILELOCATION on host $(hostname)"
    urxvt -bg rgba:1500/1000/3000/9999 -fg rgba:9999/cccc/eeee/eeee +sb -e vim ${FILELOCATION}
    echo $STRING >> $LOGLOCATION
    cd $NOTEDIR
    git add $FILELOCATION
    git add $LOGLOCATION
    git commit -m $STRING
    if [[ -n `git show-ref` ]] 
    then
        git push
    fi
fi
