#!/usr/bin/env zsh
NOTEDIR=${HOME}/Git/notes/
cd $NOTEDIR
NOTE=`ls -1 ${NOTEDIR} | dmenu -b -nb darkred -nf pink -sb red -sf pink`
FILELOCATION="${NOTEDIR}${NOTE}"
LOGLOCATION="${NOTEDIR}notes.log"
mkdir -p ${NOTEDIR}
if [[ -n $NOTE ]] 
then
    TIMESTAMP=`date`
    STRING="$TIMESTAMP : removed file $FILELOCATION from host $(hostname)"
    urxvt -bg rgba:1500/1000/3000/9999 -fg rgba:9999/cccc/eeee/eeee +sb -e rm -rf ${FILELOCATION}
    echo $STRING >> $LOGLOCATION
    cd $NOTEDIR
    git rm --ignore-unmatch --quiet --force $FILELOCATION
    git add $LOGLOCATION
    git commit -m $STRING
    if [[ -n `git show-ref` ]] 
    then
        git push
    fi
fi
